name: Build Rootless Tweak

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Theos
      uses: actions/checkout@v3
      with:
        repository: theos/theos
        ref: master
        path: theos
        submodules: recursive

    - name: Build Package
      run: |
        export THEOS=$GITHUB_WORKSPACE/theos
        export PATH=$THEOS/bin:$PATH
        make package FINALPACKAGE=1

    - name: Upload DEB Artifact
      uses: actions/upload-artifact@v3
      with:
        name: CowbellBattery-DEB
        path: packages/*.deb
