name: Build SimpleCowbell Rootless

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest  # 切換至 macOS 環境
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Tweak Package
        run: |
          make clean
          make package ROOTLESS=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleCowbell-deb
          path: packages/*.deb
